# Generated by Django 5.2.12 on 2026-03-10 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categorie'),
        ),
    ]
